language: node_js
services:
  - docker
env:
  # Necessary if we're running a service manually instead of
  # using prodStart.sh or devStart.sh
  - MONGO_URL="mongodb://mongo:27017/MedBook"
install:
  # Build all containers
  - docker-compose -f docker-compose-build.yml build
  # Start up mongo
  - docker-compose -f docker-compose-mongo.yml up -d
  # for now, just start up wrangler normally
  - docker-compose -f docker-compose.yml -f docker-compose-test.yml run -d wrangler
script:
  # Run some jobrunner tests 
  - docker-compose -f docker-compose.yml -f docker-compose-test.yml run job-runner
  # is it running?
  - docker ps
