language: node_js
services:
  - docker
install:
  - docker-compose -f docker-compose-build.yml build
  # Just run jobrunner for now
  - docker-compose run job-runner
script:
  # is it running?
  - docker ps
