version: '2'
services:
  job-runner:
    container_name: "job-runner"
    restart: always
    image: medbook/job-runner:v1.0.9
    volumes:
      - ./jobrunner/external-tools:/external-tools
      - /filestore:/filestore
    environment:
      ROOT_URL: http://0.0.0.0:8000/job-runner
      WORLD_URL:
      MONGO_URL:
      MAIL_URL:
      METEOR_SETTINGS: '{"limma_path":"/external-tools/limma/limma_ng.R","outlier_analysis":"/external-tools/OutlierAnalysis/outlier-analysis.sh","calculate_outlier_genes":"/external-tools/OutlierAnalysis/calculate_outlier_genes.R","genomic_expression_export":"/external-tools/exporters/genomic_expression_export.py","gene_set_group_export":"/external-tools/exporters/gene_set_group_export.py","limma_phenotype_export":"/external-tools/exporters/limma_phenotype_export.py","gsea_path":"/external-tools/gsea/rgGSEA.py","gsea_jar_path":"/external-tools/gsea/gsea2-2.2.2.jar","python":"python","expression_level_gene_filter":"/external-tools/ExpressionAndVarianceFilters/filter_out_genes_unexpressed_in_most_samples.py","variance_gene_filter":"/external-tools/ExpressionAndVarianceFilters/filter_out_lowest_varying_genes.py"}'
  wrangler:
    container_name: "wrangler"
    image: medbook/wrangler:v1.0.4
    restart: always
    environment:
      ROOT_URL: http://0.0.0.0:8000/wrangler
      WORLD_URL:
      MONGO_URL:
      MAIL_URL:
