version: '2'
services:
  patient-care:
    build:
      context: .
      dockerfile: ./patient-care/Dockerfile
      args:
        appdir: patient-care
  job-runner:
    build:
      context: .
      dockerfile: ./job-runner/Dockerfile
      args:
        appdir: job-runner
  wrangler:
    build:
      context: .
      dockerfile: ./wrangler/Dockerfile
      args:
        appdir: wrangler
