# NOTE: this file should only be used in development as it
# mounts /data/db to /mnt, which can disappear at any time.

version: '2'
services:
  mongo:
    container_name: "mongo"
    restart: always
    image: mongo:3.2.10
    # allows contact with mongo from localhost outside a container
    ports:
      - "127.0.0.1:27017:27017"
    volumes:
      - /mnt/data/db:/data/db
