version: '2'
services:
  job-runner:
    build:
      context: .
      dockerfile: ./job-runner/Dockerfile
      args:
        appdir: job-runner
  wrangler:
    build:
      context: .
      dockerfile: ./wrangler/Dockerfile
      args:
        appdir: wrangler
