version: '2'
services:
  # NOTE: appdir is consumed in the ONBUILD commands in the meteor base image
  # Dockerfile

  patient-care:
    build:
      context: .
      dockerfile: ./patient-care/Dockerfile
      args:
        appdir: patient-care
  job-runner:
    build:
      context: .
      dockerfile: ./job-runner/Dockerfile
      args:
        appdir: job-runner
  wrangler:
    build:
      context: .
      dockerfile: ./wrangler/Dockerfile
      args:
        appdir: wrangler

  gateway:
    build:
      context: .
      dockerfile: ./gateway/Dockerfile

  cbioportal:
    build:
      context: .
      dockerfile: ./cbioportal/Dockerfile
