version: '2'
services:
  patient-care:
    build:
      context: .
      dockerfile: patientcare/Dockerfile
      args:
        appdir: patientcare
    image: medbook/patient-care:v1.0.5
  job-runner:
    build:
      context: .
      dockerfile: ./job-runner/Dockerfile
      args:
        appdir: job-runner
  wrangler:
    build:
      context: .
      dockerfile: ./wrangler/Dockerfile
      args:
        appdir: wrangler
