version: '2'
services:
  patient-care:
    build:
      context: .
      dockerfile: patientcare/Dockerfile
      args:
        appdir: patientcare
    image: medbook/patient-care:v1.0.5
  job-runner:
    build:
      context: .
      dockerfile: jobrunner/Dockerfile
      args:
        appdir: jobrunner
    image: medbook/job-runner:v1.0.9
  wrangler:
    build:
      context: .
      dockerfile: wrangler/Dockerfile
      args:
        appdir: wrangler
    image: medbook/wrangler:v1.0.4
