version: '2'
services:
  job-runner:
    build:
      context: .
      dockerfile: ./jobrunner/Dockerfile
      args:
        appdir: jobrunner
  wrangler:
    build:
      context: .
      dockerfile: ./wrangler/Dockerfile
      args:
        appdir: wrangler
