version: '2'
services:
  job-runner:
    build:
      context: .
      dockerfile: jobrunner/Dockerfile
      args:
        appdir: jobrunner
    image: medbook/job-runner:v1.0.9
  wrangler:
    build:
      context: .
      dockerfile: wrangler/Dockerfile
      args:
        appdir: wrangler
    image: medbook/wrangler:v1.0.4
