version: '2'
services:
  job-runner:
    build:
      context: .
      dockerfile: jobrunner/Dockerfile
    image: test/jobrunner_test
  #wrangler:
  #  command: /app-dev/dockerDev.sh
  #  volumes:
  #  - ./wrangler/webapp:/app-dev
  #  - ./packages:/packages
  #  environment:
  #    PACKAGE_DIRS: "/packages"
  #mongo:
  #  container_name: "mongo"
  #  restart: always
  #  image: mongo:2.6.12
  #  # allows contact with mongo from localhost outside a container
  #  ports:
  #    - "127.0.0.1:27017:27017"
